sensor:
  - platform: integration
    source: sensor.sds_power_consumption
    name: sds_power_integration
    unit_prefix: 'k'
    round: 3
  - platform: integration
    source: sensor.sds_water_consumption
    method: left
    name: sds_water_integration
    unit: 'm³'
    round: 2
  - platform: integration
    source: sensor.sds_gas_consumption
    method: left
    name: sds_gas_integration
    unit: 'm³'
    round: 2

utility_meter:
  sds_power_hourly:
    source: sensor.sds_power_integration
    cycle: hourly
  sds_water_hourly:
    source: sensor.sds_water_integration
    cycle: hourly
  sds_gas_hourly:
    source: sensor.sds_gas_integration
    cycle: hourly
  sds_power_daily:
    source: sensor.sds_power_integration
    cycle: daily
  sds_water_daily:
    source: sensor.sds_water_integration
    cycle: daily
  sds_gas_daily:
    source: sensor.sds_gas_integration
    cycle: daily
  sds_power_monthly:
    source: sensor.sds_power_integration
    cycle: monthly
  sds_water_monthly:
    source: sensor.sds_water_integration
    cycle: monthly
  sds_gas_monthly:
    source: sensor.sds_gas_integration
    cycle: monthly
