# SDS 월패드 공동현관 문열림 예약

input_boolean:
  # 예약 버튼 등록
  reserve_public_open:
    name: "공동현관 예약"
    icon: mdi:door-closed-lock

automation:
  # 예약 중에 공동현관 초인종 울리는 경우, 3초 후 문을 열고 예약은 끕니다.
  # 주의: 외부인이 "이 집은 항상 자동으로 열린다" 고 인식하면 불편하거나 위험할 수 있으니,
  #       delay 시간 조절이나 예약 자동해제의 수정은 신중히 결정하세요.
  - alias: public_gate_open
    trigger:
      - platform: state
        entity_id: switch.sds_intercom_public
        from: unavailable
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.reserve_public_open
        state: "on"
    action:
      - delay: '00:00:03'
      - service: switch.turn_on
        entity_id: switch.sds_intercom_public
      - service: input_boolean.turn_off
        entity_id: input_boolean.reserve_public_open
